### ISSUE TITLE
Tooltip marker can't set to gradient color

### ISSUE THREAD

**Issue by linw1995** [antvis/g2#525]
* **G2 Version**:
3.0.5-beta.5

* **Platform**:
Chrome

* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/13523027/37261259-13a75fe6-25d6-11e8-83df-28a17c624830.png)

* **CodePen Link**:
[g2-github-issue](https://codepen.io/linw1995/pen/WzvMjz)

Tooltip marker can't set to gradient color. 
After setting to gradient color, it goes transparent unexpectedly.

**Comment by linw1995** [comment]
的确可以用 `itemTpl`  来实现这个效果。不过这个bug，不应该花时间解决吗？
https://github.com/antvis/g2/blob/e32ac0b7abf25c60bc22b1f3bef2a81f97013c0e/src/component/tooltip/index.js#L242-L257
在这函数内，`color`若是这样的形式`l(270) 0:#f16522 1:#fdac00`，把它转换成 **CSS渐变** 来实现？。

**Comment by linw1995** [comment]
## 方法一
```js
chart.tooltip({
  itemTpl:
    '<li data-index={index} class="custom-tooltip-marker"><span style="width:8px;height:8px;border-radius:50%;display:inline-block;margin-right:8px;"></span>{name}: {value}</li>'
});
```
```css
li.custom-tooltip-marker[data-index="0"] > span {
  background: linear-gradient(to bottom, #07c5e6, #00fefe);
}
li.custom-tooltip-marker[data-index="1"] > span {
  background: linear-gradient(to bottom, #f16522, #fdac00);
}
```
出效果了
![image](https://user-images.githubusercontent.com/13523027/37273256-34aa5444-2614-11e8-8863-f6e302c910b3.png)
不过……
![image](https://user-images.githubusercontent.com/13523027/37273294-4a8223fa-2614-11e8-8a60-981b60c58ee9.png)

## 方法二

```js
chart.tooltip({
  itemTpl:
    '<li data-index={index} class="custom-tooltip-marker-for-{name}"><span style="width:8px;height:8px;border-radius:50%;display:inline-block;margin-right:8px;"></span>{name}: {value}</li>'
});
```
```css
li.custom-tooltip-marker-for-London > span {
  background: linear-gradient(to bottom, #07c5e6, #00fefe);
}
li.custom-tooltip-marker-for-Berlin > span {
  background: linear-gradient(to bottom, #f16522, #fdac00);
}
```
这样倒是不错，……无论法一法二，复用太麻烦了。如果要成为通用组件，还要再封装一层。
